### ISSUE TITLE
BOSS-RUNS with Minknow 23.07.5 

### ISSUE THREAD

**Issue by gchevignon** [goldman-gp-ebi/BOSS-RUNS#4]
Hi,
Is BOSS-RUNS ready for Minknow 23.07.5 with Dorado integration ?
If not, any idea on how to use guppy instead of dorado with this last version of Minknow ?
Best,
Germain

**Comment by W-L** [comment]
Hi Germain,
Apologies for the embarrassingly long time it took me to get back to you. The repository just got a big update, among other things to bring it up to date with newer versions of readfish and ONT's software. I've tested it with MinKNOW version 23.11.4 and dorado 7.2.13. Packaging of the code has also been updated, so it is now easier to install. Please see the readme for that.
Again my apologies!
